### ISSUE TITLE
Cannot compile/run project

### ISSUE THREAD

**Issue by alth4669** [Gsenor/Final-project#1]
Hi there! I'm unable to download/install this project successfully. There are multiple versions of your main.cpp file and I can't get any of them to compile. Your README said that you did not encounter any issues while running the project. Can you please explain how to get the program installed and running successfully? Thanks!

**Comment by Gsenor** [comment]
Hey. There have been some issues with the project and github for some reason. I had to retool it to be used with code blocks and uploaded it as a code blocks project in order to get it to work. However that also lead to a bug that I simply don't have time to fix. That will make a great contribution for the second half of phase 3. I apologize for any inconvenience.

**Comment by Gsenor** [comment]
It is under the folder final project take 2

**Comment by alth4669** [comment]
Got it. Can now download and run the executable.
